### ISSUE TITLE
PHP Warning: "resource" is not a supported builtin type and will be interpreted as a class name.

### ISSUE THREAD

**Issue by insign** [hexydec/cssdoc#4]
PHP Warning:  "resource" is not a supported builtin type and will be interpreted as a class name. Write "\hexydec\css\resource" or import the class with "use" to suppress this warning in /var/www/html/vendor/hexydec/cssdoc/src/cssdoc/cssdoc.php on line 84

Looks like PHP 8 does not support resource anymore. Change to mixed can fix.

**Comment by insign** [comment]
44a193e might fixed this but you need update at https://github.com/hexydec/htmldoc too.

**Comment by insign** [comment]
Made a PR #5

**Comment by insign** [comment]
Not sure, but I think you need create a new tag to update at htmldoc.

**Comment by hexydec** [comment]
I have updated the dependencies in HTMLDoc and released a new version, plese update to 1.2.1.
