### ISSUE TITLE
FatalError

### ISSUE THREAD

**Issue by robiul215** [hexydec/cssdoc#6]
here is the error for laravel please check.
I am using
PHP-> 7.4.27 
Laravel-> 8.75
Declaration of hexydec\css\cssdoc::offsetGet(hexydec\css\mixed $i): hexydec\css\mixed must be compatible with ArrayAccess::offsetGet($offset)
https://prnt.sc/CqdaJzuk37TS

**Comment by robiul215** [comment]
The problem is solved now
just replace this code
##########
	public function offsetGet($i) { // return reference so you can set it like an array
		if (isset($this->children[$i])) {
			$obj = new cssdoc($this->config);
			$obj->collection([$this->children[$i]]);
			return $obj;
		}
		return null;
	}
#########

**Comment by hexydec** [comment]
Yes there was an error that prevented compatibility with PHP 7.4, please updated to the latest version to solve.
