### ISSUE TITLE
Added support for min and max (so it doesn't break css calculation)

### ISSUE THREAD

**Issue by theperfectwill** [hexydec/cssdoc#8]
Hi.

In `$config` at

https://github.com/hexydec/cssdoc/blob/06da9d0dd7f0dbd806f9e4bbf2b846a0226ddaa0/src/cssdoc.php#L37

`spaced` needs the keywords: `min` and `max` as well, otherwise the `*` used in min and max (**or perhaps elsewhere in css?**) breaks.

I say elsewhere, because maybe it is better to declare that `*` always have surrounding space around it? In `min` and `max`, if the `*` does not have space around it, it breaks the calculation. Which some time ago on a different project, took me a long time to figure out that! Lol - so it didn't take that long this time (whewww)

I added them locally to support this like:

```php
'spaced' => ['calc', 'min', 'max'],
```

**Comment by hexydec** [comment]
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/min), only the `+` and `-` operands require a space to be left:

_"Make sure to put a space on each side of the + and - operands"_

Also the `clamp()` function will require this upgrade.

**Comment by theperfectwill** [comment]
Great. Everything works as well on my side. Appreciate the updates.
